name: Package Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: wget -O - https://gist.githubusercontent.com/thiagocordeiro/535feba34546cd4db8c0622a7e74f5bf/raw | bash

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: zend.assertions=1, assert.active=1, assert.bail=0, assert.exception=1, assert.warning=1
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Tests
        run: composer tests

      - name: Mutation tests
        run: composer mutation

      - name: Mutation Report
        run: cat .infection.log
        if: ${{ always() }}
